# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddAccount.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddAccount(object):
    def setupUi(self, AddAccount):
        AddAccount.setObjectName("AddAccount")
        AddAccount.resize(728, 409)
        font = QtGui.QFont()
        font.setPointSize(11)
        AddAccount.setFont(font)
        self.formLayout = QtWidgets.QFormLayout(AddAccount)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(AddAccount)
        self.label_4.setStyleSheet("font: 18pt \"Leelawadee UI Semilight\";\n"
"")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_4)
        self.label = QtWidgets.QLabel(AddAccount)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(AddAccount)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(AddAccount)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(AddAccount)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_3 = QtWidgets.QLabel(AddAccount)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(AddAccount)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_5 = QtWidgets.QLabel(AddAccount)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(AddAccount)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_4)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtWidgets.QLabel(AddAccount)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(AddAccount)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_6 = QtWidgets.QLineEdit(AddAccount)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout.addWidget(self.lineEdit_6)
        self.lineEdit_5 = QtWidgets.QLineEdit(AddAccount)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout.addWidget(self.lineEdit_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.formLayout.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.verticalLayout)
        self.AddAccountBtn = QtWidgets.QPushButton(AddAccount)
        self.AddAccountBtn.setObjectName("AddAccountBtn")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.AddAccountBtn)

        self.retranslateUi(AddAccount)
        QtCore.QMetaObject.connectSlotsByName(AddAccount)

    def retranslateUi(self, AddAccount):
        _translate = QtCore.QCoreApplication.translate
        AddAccount.setWindowTitle(_translate("AddAccount", "Form"))
        self.label_4.setText(_translate("AddAccount", "Добаление аккаунта"))
        self.label.setText(_translate("AddAccount", "Название"))
        self.label_2.setText(_translate("AddAccount", "Логин"))
        self.label_3.setText(_translate("AddAccount", "Пароль"))
        self.label_5.setText(_translate("AddAccount", "Прокси"))
        self.lineEdit_4.setPlaceholderText(_translate("AddAccount", "127.0.0.0:80"))
        self.label_7.setText(_translate("AddAccount", "Логин"))
        self.label_6.setText(_translate("AddAccount", "Пароль"))
        self.AddAccountBtn.setText(_translate("AddAccount", "Добавить"))
