# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddPublic.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddPublic(object):
    def setupUi(self, AddPublic):
        AddPublic.setObjectName("AddPublic")
        AddPublic.resize(400, 300)
        font = QtGui.QFont()
        font.setPointSize(11)
        AddPublic.setFont(font)
        self.formLayout = QtWidgets.QFormLayout(AddPublic)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(AddPublic)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(AddPublic)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(AddPublic)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(AddPublic)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.pushButton = QtWidgets.QPushButton(AddPublic)
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.pushButton)

        self.retranslateUi(AddPublic)
        QtCore.QMetaObject.connectSlotsByName(AddPublic)

    def retranslateUi(self, AddPublic):
        _translate = QtCore.QCoreApplication.translate
        AddPublic.setWindowTitle(_translate("AddPublic", "Form"))
        self.label.setText(_translate("AddPublic", "Название"))
        self.label_2.setText(_translate("AddPublic", "Ссылка"))
        self.pushButton.setText(_translate("AddPublic", "Добавить"))
