# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1347, 599)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.DelSelect = QtWidgets.QComboBox(self.centralwidget)
        self.DelSelect.setObjectName("DelSelect")
        self.horizontalLayout.addWidget(self.DelSelect)
        self.DelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.DelBtn.setObjectName("DelBtn")
        self.horizontalLayout.addWidget(self.DelBtn)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.AddAccounts = QtWidgets.QPushButton(self.centralwidget)
        self.AddAccounts.setObjectName("AddAccounts")
        self.gridLayout.addWidget(self.AddAccounts, 2, 0, 1, 1)
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setObjectName("table")
        self.table.setColumnCount(9)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(8, item)
        self.table.horizontalHeader().setCascadingSectionResizes(False)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.table, 0, 0, 1, 1)
        self.Publics = QtWidgets.QPushButton(self.centralwidget)
        self.Publics.setObjectName("Publics")
        self.gridLayout.addWidget(self.Publics, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1347, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.DelBtn.setText(_translate("MainWindow", "Удалить аккаунт"))
        self.AddAccounts.setText(_translate("MainWindow", "Добавить аккаунты"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Запуск"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Прокси"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Аккаунт"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Лайк"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Комментарий"))
        item = self.table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Ссылка"))
        item = self.table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Текст коментария"))
        item = self.table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Задержка"))
        item = self.table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Статус выполнения задачи"))
        self.Publics.setText(_translate("MainWindow", "Паблики для автолайкинга"))
