# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Publics.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Public(object):
    def setupUi(self, Public):
        Public.setObjectName("Public")
        Public.resize(954, 546)
        font = QtGui.QFont()
        font.setPointSize(11)
        Public.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(Public)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.list = QtWidgets.QTableWidget(Public)
        self.list.setObjectName("list")
        self.list.setColumnCount(3)
        self.list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.list.setHorizontalHeaderItem(2, item)
        self.list.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.list)
        self.AddPublic = QtWidgets.QPushButton(Public)
        self.AddPublic.setObjectName("AddPublic")
        self.verticalLayout.addWidget(self.AddPublic)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.DeletSelect = QtWidgets.QComboBox(Public)
        self.DeletSelect.setObjectName("DeletSelect")
        self.horizontalLayout.addWidget(self.DeletSelect)
        self.DeletePublic = QtWidgets.QPushButton(Public)
        self.DeletePublic.setObjectName("DeletePublic")
        self.horizontalLayout.addWidget(self.DeletePublic)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Public)
        QtCore.QMetaObject.connectSlotsByName(Public)

    def retranslateUi(self, Public):
        _translate = QtCore.QCoreApplication.translate
        Public.setWindowTitle(_translate("Public", "Form"))
        item = self.list.horizontalHeaderItem(0)
        item.setText(_translate("Public", "Id"))
        item = self.list.horizontalHeaderItem(1)
        item.setText(_translate("Public", "Название"))
        item = self.list.horizontalHeaderItem(2)
        item.setText(_translate("Public", "Ссылка"))
        self.AddPublic.setText(_translate("Public", "Добавить паблик"))
        self.DeletePublic.setText(_translate("Public", "Удалить паблик"))
